### Introduction to importing CSV and using pandas

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [2]:
health = pd.read_csv("/Users/ap/Python/PythonData/DataSets/synthetic_health_lifestyle_dataset.csv")

In [3]:
health.head(10)

,ID,Age,Gender,Height_cm,Weight_kg,BMI,Smoker,Exercise_Freq,Diet_Quality,Alcohol_Consumption,Chronic_Disease,Stress_Level,Sleep_Hours
0,1,56,Other,177.6,37.3,11.8,Yes,NaN,Poor,NaN,No,9,8.5
1,2,69,Other,169.3,70.7,24.7,No,1-2 times/week,Good,High,No,2,5.9
2,3,46,Female,159.1,69.0,27.3,No,Daily,Excellent,Moderate,No,3,4.8
3,4,32,Male,170.6,76.4,26.3,No,3-5 times/week,Excellent,Moderate,No,9,6.6
4,5,60,Male,158.4,60.4,24.1,No,3-5 times/week,Excellent,Low,Yes,6,6.1
5,6,25,Female,167.7,62.0,22.0,No,Daily,Good,Moderate,No,1,5.8
6,7,38,Other,152.5,88.0,37.8,No,1-2 times/week,Good,High,Yes,2,5.8
7,8,56,Male,165.3,65.0,23.8,No,Daily,Good,Moderate,No,7,6.8
8,9,36,Male,176.9,41.3,13.2,No,Daily,Average,NaN,No,6,6.3
9,10,40,Other,162.0,77.4,29.5,Yes,1-2 times/week,Good,Low,Yes,1,5.6

In [4]:
health.tail(10)

,ID,Age,Gender,Height_cm,Weight_kg,BMI,Smoker,Exercise_Freq,Diet_Quality,Alcohol_Consumption,Chronic_Disease,Stress_Level,Sleep_Hours
7490,7491,24,Other,153.9,51.7,21.8,No,1-2 times/week,Excellent,High,No,7,9.7
7491,7492,44,Male,155.1,81.5,33.9,Yes,3-5 times/week,Excellent,Low,No,7,7.5
7492,7493,18,Female,175.6,59.7,19.4,No,3-5 times/week,Good,Moderate,No,10,7.8
7493,7494,44,Other,152.7,73.6,31.6,No,3-5 times/week,Excellent,Low,No,6,5.4
7494,7495,33,Female,163.8,78.1,29.1,Yes,NaN,Good,NaN,No,10,6.1
7495,7496,55,Other,168.3,52.4,18.5,Yes,1-2 times/week,Average,Moderate,Yes,4,5.5
7496,7497,24,Male,179.1,58.8,18.3,No,3-5 times/week,Excellent,Moderate,No,5,7.6
7497,7498,61,Other,160.2,80.0,31.2,No,3-5 times/week,Poor,Moderate,No,5,6.2
7498,7499,40,Female,172.6,66.1,22.2,No,1-2 times/week,Good,Low,No,9,6.1
7499,7500,58,Other,163.8,59.3,22.1,No,Daily,Excellent,Low,No,6,8.1

In [5]:
health.index

RangeIndex(start=0, stop=7500, step=1)

In [6]:
health.columns

Index(['ID', 'Age', 'Gender', 'Height_cm', 'Weight_kg', 'BMI', 'Smoker',
       'Exercise_Freq', 'Diet_Quality', 'Alcohol_Consumption',
       'Chronic_Disease', 'Stress_Level', 'Sleep_Hours'],
      dtype='object')